### ISSUE TITLE
[Feature]: Juxtaposition rules

### ISSUE THREAD

**Issue by piplupness** [PretendoNetwork/juxtaposition-ui#94] opened 2024-09-09 13:24 UTC
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

Rules. Basically a way to allow users to read the rules again after signing up.

### Why do you want to have this feature?

Having rules can help with moderation, and clear up any confusion to the community about what is and what is not allowed.

### Any other details to share? (OPTIONAL)

While am I at it, limiting from posting is not prompting the reason (no error code 598-0009) and hopefully a way to mods to issue a warning similar to how Miiverse used to before issuing to limitations or bans. (For example if we delete a post because it mentions piracy we can send them a warning to not talk about it)

**Comment by jonbarrow** [comment] 2024-09-15 19:11
This is my fault, I told you on Discord to make an issue but I did not realize one already existed. Duplicate of #72

**Closed by jonbarrow** 2024-09-15 19:11 UTC
Labels: awaiting-approval, feature
